debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[file]
  directory = "/trconf/"
  watch = true

[acme]
email = "rinormaloku@gmail.com"
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
storage = "acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
